name: PyAppify
description: Use PyAppify to package your python app
author: ok-oldking

inputs:
  version:
    description: The tag version of pyappify to use. Defaults to the latest tag. Strongly recommended to set to ensure consistancy.
    required: false

outputs:
  dist-path:
    description: The path to the directory containing the zipped application bundles.

  pyappify-assets:
    description: The list of files to be released.

runs:
  using: 'node23'
  main: 'index.js'

branding:
  icon: package
  color: blue